name: hello-world

on:
  schedule:
    - cron: "* * * * *" # Exécute toutes les minutes
  push: # Vous pouvez garder cet événement si vous souhaitez également exécuter le workflow lors d'un push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
